Update asturias.json
PucelaBits/websegura pull request #208
Opened 2021-03-13 13:53 UTC by XtoreX

2021-03-14 09:09 UTC, XtoreX commented
issues #190 y #194

2021-03-16 18:49 UTC, adrm requested changes
Veo problemas con los tags, deberían usarse exactamente los strings del tags.json, y de querer añadir nuevas categorías deberían añadirse a dicho fichero, habría que revisarlo.

2021-03-16 18:49 UTC, adrm commented on _data/provincias/asturias.json
> +      "tags": ["fundaciones"]
Esto no suena a fundación, ¿seguro que lo es?

2021-03-16 19:12 UTC, XtoreX commented
No, es un error, lo reviso


Un saludo

Cristóbal Megido Almaraz

El mar., 16 mar. 2021 19:50, Adrián de la Rosa ***@***.***>
escribió:

> ***@***.**** requested changes on this pull request.
>
> Veo problemas con los tags, deberían usarse exactamente los strings del
> tags.json, y de querer añadir nuevas categorías deberían añadirse a dicho
> fichero, habría que revisarlo.
> ------------------------------
>
> In _data/provincias/asturias.json
> <https://github.com/PucelaBits/websegura/pull/208#discussion_r595452593>:
>
> > @@ -23,7 +73,8 @@
>
>      {
>
>        "url": "www.facc.info",
>
>        "name": "Federación Asturiana de Concejos",
>
> -      "twitter": "RedConsolida"
>
> +      "twitter": "RedConsolida",
>
> +      "tags": ["fundaciones"]
>
>
> Esto no suena a fundación, ¿seguro que lo es?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PucelaBits/websegura/pull/208#pullrequestreview-613611229>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD2HGVD5Q6BN57GYUV5LKLDTD6R6JANCNFSM4ZD27FXQ>
> .
>

2021-03-16 20:07 UTC, XtoreX commented on _data/provincias/asturias.json
> +      "tags": ["fundaciones"]
corregido ;-)

2021-03-17 13:29 UTC, closed without merging