Estatal
PucelaBits/websegura pull request #98
Opened 2021-02-09 23:52 UTC by cuantocarlos

Actualización estatal

2021-02-09 23:59 UTC, javierprovecho requested changes

2021-02-09 23:59 UTC, javierprovecho commented on _data/general.json
> +}
```suggestion
},
```

2021-02-10 00:06 UTC, javierprovecho requested changes

2021-02-10 00:06 UTC, javierprovecho commented on _data/general.json
> +  "url": "ine.es",
duplicated

https://github.com/PucelaBits/websegura/blob/dc92f564b079e196ca1f858619c5bcd0a891906b/_data/general.json#L154-L158

2021-02-10 00:12 UTC, cuantocarlos commented on _data/general.json
> +  "url": "ine.es",
resuelto

2021-02-10 07:44 UTC, palmerabollo approved these changes

2021-02-10 07:45 UTC, merged